### ISSUE TITLE
"schema" in "SchemaExtractorConfig" shadows an attribute in parent "BaseModel"

### ISSUE THREAD

**Issue by ritwikraha** [tensorlakeai/indexify-extractors#199]
https://github.com/tensorlakeai/indexify-extractors/blob/0ad8d66d11589db9480684dec63a8231336eb876/text/schema/schema_extractor.py#L14

The above code causes the warning in some scenarios:

```
You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_fields.py:200: UserWarning: Field name "schema" in "SchemaExtractorConfig" shadows an attribute in parent "BaseModel"
  warnings.warn(
```

In other scenarios, it fails with the following error message:

```
Traceback (most recent call last):
  File "/content/indexify-extractors/text/schema/schema_extractor.py", line 10, in <module>
    class SchemaExtractorConfig(BaseModel):
  File "pydantic/main.py", line 186, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/utils.py", line 167, in pydantic.utils.validate_field_name
NameError: Field name "schema" shadows a BaseModel attribute; use a different field name with "alias='schema'".
```
The issue seems to be that the name "schema" is reserved by Pydantic's BaseModel for its own internal use.

**Comment by ritwikraha** [comment]
Has been fixed by https://github.com/tensorlakeai/indexify-extractors/pull/200
